#!/bin/bash

prop=../out/prop.smt2


e() {

tip --skolemise-conjecture --tff $1 | ../.stack-work/install/x86_64-linux/lts-7.7/8.0.1/bin/jukebox fof /dev/stdin 2>/dev/null | eproof --tstp-in --auto  --silent >& /dev/null

}

e_dir() {
    for i in $1/*; do
        if ! e $i; then
          return 1
        fi
    done
}

n=0
m=0

while true; do

    if tip --select-conjecture $n >& /dev/null "$prop"; then
        goal=$(cat "$prop"|tip --select-conjecture $n) 

        while true; do
            dir=$(mktemp -d)
            if echo "$goal"|tip --induction "[$m]" - $dir >& /dev/null; then
                echo "Created obligations proof"
                  if dir_e $dir $1; then
                    # Success!
                    rm -r $dir
                    return
                  else
                    rm -r $dir
                    ((m=$m+1))
                  fi
            else
              # Tried all variables unsuccessfully - fail.
              rm -r $dir
              return 1
            fi

        done
        rm -r $dir
        ((n=$n+1))
    else
        break;
    fi

done



